# This is a basic workflow to help you get started with Actions

name: BuildISO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --privileged

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          cd archiso
          pwd

      # Build ISO
      - run: pacman -Sy --noconfirm archiso rsync sshpass
        shell: bash
      - run: cd archiso && mkarchiso -v .
        shell: bash
      - run: sshpass -e rsync -rtv archiso/out/ mearch@frs.sourceforge.net:/home/frs/project/mearch/mearchiso
        shell: bash
        env:
          RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
          SSHPASS: ${{ secrets.RSYNC_PASSWORD }}
        
      # - name: Upload ISO
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: archlinux-iso
      #     path: archiso/out

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
