# This is a basic workflow to help you get started with Actions

name: RepoBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "repoBuild" ]
  pull_request:
    branches: [ "repoBuild" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: OL

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Docker Build
        run: cd repo && docker build -t archpkgbuilder:v1 . && docker images
        shell: bash
      - name: Building
        run: |
          chmod -R 777 repo
          chmod +x repo/build-pkgs-and-pub-repo.sh
          docker run --rm -v $(pwd):/app archpkgbuilder:v1 /bin/bash -c 'cd /app && ./repo/build-pkgs-and-pub-repo.sh'
        shell: bash
      - name: Show
        run: |
          ls -al repo/mearch-os-repo.tar.gz
      # rsync repo tar.gz
      - uses: up9cloud/action-rsync@master
        env:
          HOST: frs.sourceforge.net
          USER: mearch
          PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
          ARGS: -azv --exclude=/.git/ --exclude=/.github/
          MODE: push
          SOURCE: repo/mearch-os-repo.tar.gz
          TARGET: /home/frs/project/mearch/package/mearch-os-repo.tar.gz
          VERBOSE: true
      # rsync x86_64 list
      - uses: up9cloud/action-rsync@master
        env:
          HOST: frs.sourceforge.net
          USER: mearch
          PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
          ARGS: -azv --delete --exclude=/.git/ --exclude=/.github/
          MODE: push
          SOURCE: repo/x86_64/
          TARGET: /home/frs/project/mearch/package/x86_64/
          VERBOSE: true
        
      # - name: Upload ISO
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: archlinux-iso
      #     path: archiso/out

      # Runs a set of commands using the runners shell
      - name: Dir Display
        run: |
          ls -al 
